@startuml
start
:CCC entscheidet über die Inhalte;
if (Kommentar löschen?) then (ja)
    if(Teammitglied?) then (ja)
        :Kommentarfunktion einfrieren;
    else
        :Gastkommentar löschen;
    endif
elseif (Beitrag/Posting entfernen?) then (ja)
    :Projektposting entfernen;
elseif (User sperren?) then (ja)
    :User sperren;
endif
stop
@enduml