@startuml
start
:CCC entscheidet über
das Projekt;
:Projekttitel wählen;
:Layout-Muster für
Projektseite wählen;
if (Ist CCC im Auftrag einer Organisation?) then (ja)
    :Antrag an fakultäre
    Organisation stellen;
    if (Genehmigung erhalten?) then (ja)
        :Fakultäre Kennzeichnung
        auf der Projektseite;
    else (nein)
        :Keine Kennzeichnung;
    endif
else (nein)
    :fakultäre Kennzeichnung
    nicht erforderlich;
endif
stop
@enduml