@startuml
start
if (Projekt anlegen) then (ja)
	:Projekt und -seite einrichten;
	if (Projekt stilllegen) then (ja)
		:Projekt stilllegen;
	else
		:Projektteilnehmer
		verwalten;
		:Inhalte verwalten;
		:Projekt koordinieren;
	endif
endif
stop
@enduml