@startuml
start
:CCC betritt Projektpinwand;
if (CCC?) then (ja)
    :Exklusive Kennzeichnung
    für CCC anzeigen;
else (nein)
    :Allgemeine Nachrichten
    an Projektpinwand aushängen;
endif
stop
@enduml